name: GitHub Pages Astro CI

on:
  # 定时更新
  schedule:
    - cron: "0 0 * * *"
  # 每次推送到 `main` 分支时触发这个“工作流程”
  # 如果你使用了别的分支名，请按需将 `main` 替换成你的分支名
  push:
    branches: [ main ]
  # 允许你在 GitHub 上的 Actions 标签中手动触发此“工作流程”
  workflow_dispatch:
  
# 允许 job 克隆 repo 并创建一个 page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: add chinese fonts
        run: sudo apt-get install fonts-wqy-zenhei
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.x.x
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          # need add cache dep , when use Puppeteer is have some problem
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm run build  
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./dist/"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
